<?php
/**
 * Albion P2P Trade — Hierarquia de categorias (4 níveis)
 *
 * $categorias_hierarquia[$cat_slug] = [$icon, $label, $subs]
 *   $subs[$sub_slug]  = [$sub_label, $itens]
 *   $itens[$item_slug] = 'Label'                  → folha (sem 4º nível)
 *                      | ['Label', $subitens]      → tem 4º nível
 *   $subitens[$si_slug] = 'Label'                 → sempre folha
 */

$categorias_hierarquia = [

    // ── Armas ──────────────────────────────────────────────────────────────
    'armas' => ['⚔', 'Armas', [
        'arcos' => ['Arcos', [
            'arco'                   => 'Arco',
            'arco-longo'             => 'Arco Longo',
            'arco-de-guerra'         => 'Arco de Guerra',
            'arco-sussurrante'       => 'Arco Sussurrante',
            'arco-plangente'         => 'Arco Plangente',
            'arco-badornico'         => 'Arco Badônico',
            'fura-brumas'            => 'Fura Brumas',
            'arco-andarilho-celeste' => 'Arco do Andarilho Celeste',
        ]],
        'bestas' => ['Bestas', [
            'besta'                  => 'Besta',
            'besta-pesada'           => 'Besta Pesada',
            'besta-leve'             => 'Besta Leve',
            'repetidor-lamentoso'    => 'Repetidor Lamentoso',
            'laca-virotes'           => 'Laça-Virotes',
            'arco-de-cerco'          => 'Arco de Cerco',
            'modelador-energia'      => 'Modelador de Energia',
            'detonadores-reluzentes' => 'Detonadores Reluzentes',
        ]],
        'machados' => ['Machados', [
            'machado-de-guerra'  => 'Machado de Guerra',
            'machadao'           => 'Machadão',
            'alabarda'           => 'Alabarda',
            'chama-corpos'       => 'Chama-Corpos',
            'seguadeira-infernal'=> 'Seguadeira Infernal',
            'patas-de-urso'      => 'Patas de Urso',
            'quebra-reinos'      => 'Quebra Reinos',
            'foice-de-cristal'   => 'Foice de Cristal',
        ]],
        'adagas' => ['Adagas', [
            'adaga'               => 'Adaga',
            'par-de-adagas'       => 'Par de Adagas',
            'garras'              => 'Garras',
            'dessangrador'        => 'Dessangrador',
            'presa-demoniaca'     => 'Presa Demoníaca',
            'mortificos'          => 'Mortíficos',
            'furia-contida'       => 'Fúria Contida',
            'gemeas-aniquiladoras'=> 'Gêmeas Aniquiladoras',
        ]],
        'martelos' => ['Martelos', [
            'martelo'             => 'Martelo',
            'martelo-elevado'     => 'Martelo Elevado',
            'martelo-de-batalha'  => 'Martelo de Batalha',
            'martelo-funebre'     => 'Martelo Fúnebre',
            'martelo-de-forja'    => 'Martelo de Forja',
            'guarda-bosques'      => 'Guarda-Bosques',
            'mao-da-justica'      => 'Mão da Justiça',
            'martelo-estrondoso'  => 'Martelo Estrondoso',
        ]],
        'luvas' => ['Luvas de Guerra', [
            'luvas-de-lutador'       => 'Luvas de Lutador',
            'bracadeiras-batalha'    => 'Braçadeiras de Batalha',
            'manoplas-cravadas'      => 'Manoplas Cravadas',
            'luvas-ursinas'          => 'Luvas Ursinas',
            'maos-infernais'         => 'Mãos Infernais',
            'cestus-golpeadores'     => 'Cestus Golpeadores',
            'punhos-de-avalon'       => 'Punhos de Avalon',
            'bracadeiras-pulsantes'  => 'Braçadeiras Pulsantes',
        ]],
        'macas' => ['Maças', [
            'maca'               => 'Maça',
            'maca-pesada'        => 'Maça Pesada',
            'mangual'            => 'Mangual',
            'maca-petrea'        => 'Maça Pétrea',
            'maca-de-incubus'    => 'Maça de Íncubus',
            'maca-cambriana'     => 'Maça Cambriana',
            'jurador'            => 'Jurador',
            'monarca-tempestuoso'=> 'Monarca Tempestuoso',
        ]],
        'bordaos' => ['Bordãos', [
            'bordao'               => 'Bordão',
            'cajado-ferreo'        => 'Cajado Férreo',
            'cajado-bilaminado'    => 'Cajado Bilaminado',
            'cajado-monge-negro'   => 'Cajado de Monge Negro',
            'seganimica'           => 'Seganímica',
            'cajado-do-equilibrio' => 'Cajado do Equilíbrio',
            'buscador-do-graal'    => 'Buscador do Graal',
            'laminas-gemeas'       => 'Lâminas Gêmeas Fantasmagóricas',
        ]],
        'lancas' => ['Lanças', [
            'lanca'           => 'Lança',
            'pique'           => 'Pique',
            'archa'           => 'Archa',
            'lanca-garceira'  => 'Lança Garceira',
            'caca-espirotos'  => 'Caça-Espíritos',
            'lanca-trina'     => 'Lança Trina',
            'alvorada'        => 'Alvorada',
            'archa-fraturada' => 'Archa Fraturada',
        ]],
        'espadas' => ['Espadas', [
            'espada-larga'         => 'Espada Larga',
            'montante'             => 'Montante',
            'espadas-dupla'        => 'Espadas Dupla',
            'lamina-aclarada'      => 'Lâmina Aclarada',
            'espada-entalhada'     => 'Espada Entalhada',
            'par-de-galatinas'     => 'Par de Galatinas',
            'cria-reis'            => 'Cria-Reis',
            'lamina-da-infinidade' => 'Lâmina da Infinidade',
        ]],
        'cajados-arcano' => ['Cajados Arcano', [
            'cajado-arcano'           => 'Cajado Arcano',
            'cajado-arcano-elevado'   => 'Cajado Arcano Elevado',
            'cajado-eniguimatico'     => 'Cajado Eniguimático',
            'cajado-feiticeiro'       => 'Cajado Feiticeiro',
            'cajado-oculto'           => 'Cajado Oculto',
            'local-malevolo'          => 'Local Malévolo',
            'som-equilibado'          => 'Som Equilíbrado',
            'cajado-astral'           => 'Cajado Astral',
        ]],
        'cajados-maldito' => ['Cajados Amaldiçoado', [
            'cajado-amaldicado'        => 'Cajado Amaldiçoado',
            'cajado-amaldicado-elevado'=> 'Cajado Amaldiçoado Elevado',
            'cajado-demoniaco'         => 'Cajado Demoníaco',
            'cajado-execrado'          => 'Cajado Execrado',
            'caveira-amaldicada'       => 'Caveira Amaldiçoada',
            'cajado-da-danacao'        => 'Cajado da Danação',
            'chama-sombras'            => 'Chama-Sombras',
            'cajado-putrido'           => 'Cajado Pútrido',
        ]],
        'cajados-fogo' => ['Cajados de Fogo', [
            'cajado-de-fogo'               => 'Cajado de Fogo',
            'cajado-de-fogo-elevado'       => 'Cajado de Fogo Elevado',
            'cajado-infernal'              => 'Cajado Infernal',
            'cajado-incendiario'           => 'Cajado Incendiário',
            'cajado-sulfuroso'             => 'Cajado Sulfuroso',
            'cajado-flamejante'            => 'Cajado Flamejante',
            'cancao-da-alvorada'           => 'Canção da Alvorada',
            'cajado-andarilho-flamejante'  => 'Cajado do Andarilho Flamejante',
        ]],
        'cajados-gelo' => ['Cajados de Gelo', [
            'cajado-de-gelo'         => 'Cajado de Gelo',
            'cajado-de-gelo-elevado' => 'Cajado de Gelo Elevado',
            'cajado-glacial'         => 'Cajado Glacial',
            'cajado-enregelante'     => 'Cajado Enregelante',
            'cajado-de-sincelo'      => 'Cajado de Sincelo',
            'prisma-geleterno'       => 'Prisma Geleterno',
            'uivo-frio'              => 'Uivo Frio',
            'cajado-artico'          => 'Cajado Ártico',
        ]],
        'cajados-sagrado' => ['Cajados Sagrado', [
            'cajado-sagrado'         => 'Cajado Sagrado',
            'cajado-sagrado-elevado' => 'Cajado Sagrado Elevado',
            'cajado-divino'          => 'Cajado Divino',
            'cajado-vivador'         => 'Cajado Avivador',
            'cajado-corrompido'      => 'Cajado Corrompido',
            'cajado-e-redencao'      => 'Cajado e Redenção',
            'queda-santa'            => 'Queda Santa',
            'cajado-exaltado'        => 'Cajado Exaltado',
        ]],
        'cajados-natureza' => ['Cajados da Natureza', [
            'cajado-da-natureza'         => 'Cajado da Natureza',
            'cajado-da-natureza-elevado' => 'Cajado da Natureza Elevado',
            'cajado-selvagem'            => 'Cajado Selvagem',
            'cajado-druidico'            => 'Cajado Druídico',
            'cajado-pustulento'          => 'Cajado Pustulento',
            'cajado-rampante'            => 'Cajado Rampante',
            'raiz-ferrea'                => 'Raíz Ferrea',
            'cajado-da-crosta-forjado'   => 'Cajado da Crosta Forjado',
        ]],
        'cajados-metamorfo' => ['Cajados Metamorfo', [
            'cajado-de-predador'      => 'Cajado de Predador',
            'cajado-enrraizado'       => 'Cajado Enrraizado',
            'cajado-primitivo'        => 'Cajado Primitivo',
            'cajado-lua-de-sangue'    => 'Cajado de Lua de Sangue',
            'cajado-endemoniado'      => 'Cajado Endemoniado',
            'cajado-runico-da-terra'  => 'Cajado Rúnico da Terra',
            'cajado-invocador-da-luz' => 'Cajado Invocador da Luz',
            'cajado-petrificante'     => 'Cajado Petrificante',
        ]],
    ]],

    // ── Armadura Peitoral ───────────────────────────────────────────────────
    'armadura-peitoral' => ['🛡', 'Peitoral', [
        'tecido' => ['Armadura de Tecido', [
            'robe-erudito'    => 'Robe de Erudito',
            'robe-clerigo'    => 'Robe de Clérigo',
            'robe-mago'       => 'Robe de Mago',
            'robe-druida'     => 'Robe de Druida',
            'robe-real'       => 'Robe Real',
            'robe-malevolo'   => 'Robe Malévolo',
            'robe-sectario'   => 'Robe Sectário',
            'robe-feerico'    => 'Robe Feerico',
            'robe-da-pureza'  => 'Robe da Pureza',
        ]],
        'couro' => ['Armadura de Couro', [
            'casaco-mercenario'      => 'Casaco de Mercenário',
            'casaco-cacador'         => 'Casaco de Caçador',
            'casaco-assassino'       => 'Casaco de Assassino',
            'casaco-espreitador'     => 'Casaco de Espreitador',
            'casaco-real'            => 'Casaco Real',
            'casaco-inferial'        => 'Casaco Inferial',
            'casaco-espectral'       => 'Casaco Espectral',
            'casaco-andarilho-nevoa' => 'Casaco de Andarilho da Névoa',
            'casaco-da-tenacidade'   => 'Casaco da Tenacidade',
        ]],
        'placa' => ['Armadura de Placa', [
            'armadura-soldado'            => 'Armadura de Soldado',
            'armadura-cavaleiro'          => 'Armadura de Cavaleiro',
            'armadura-guardiao'           => 'Armadura de Guardião',
            'armadura-guarda-tumbas'      => 'Armadura de Guarda-Tumbas',
            'armadura-real'               => 'Armadura Real',
            'armadura-demonia'            => 'Armadura Demônia',
            'armadura-judicante'          => 'Armadura Judicante',
            'armadura-tecelao-crepusculo' => 'Armadura de Tecelão do Crepúsculo',
            'armadura-da-bravura'         => 'Armadura da Bravura',
        ]],
    ]],

    // ── Armadura Capacete ───────────────────────────────────────────────────
    'armadura-capacete' => ['🪖', 'Capacete', [
        'tecido' => ['Capote de Tecido', [
            'capote-erudito'   => 'Capote de Erudito',
            'capote-clerigo'   => 'Capote de Clérigo',
            'capote-mago'      => 'Capote de Mago',
            'capote-druida'    => 'Capote de Druida',
            'capote-real'      => 'Capote Real',
            'capote-malevolo'  => 'Capote Malévolo',
            'capote-sectario'  => 'Capote Sectário',
            'capote-feerico'   => 'Capote Feerico',
            'capote-da-pureza' => 'Capote da Pureza',
        ]],
        'couro' => ['Capuz de Couro', [
            'capuz-mercenario'       => 'Capuz de Mercenário',
            'capuz-cacador'          => 'Capuz de Caçador',
            'capuz-assassino'        => 'Capuz de Assassino',
            'capuz-espreitador'      => 'Capuz de Espreitador',
            'capuz-real'             => 'Capuz Real',
            'capuz-inferial'         => 'Capuz Inferial',
            'capuz-espectral'        => 'Capuz Espectral',
            'capuz-andarilho-nevoa'  => 'Capuz de Andarilho da Névoa',
            'capuz-da-tenacidade'    => 'Capuz da Tenacidade',
        ]],
        'placa' => ['Elmo de Placa', [
            'elmo-soldado'            => 'Elmo de Soldado',
            'elmo-cavaleiro'          => 'Elmo de Cavaleiro',
            'elmo-guardiao'           => 'Elmo de Guardião',
            'elmo-guarda-tumbas'      => 'Elmo de Guarda-Tumbas',
            'elmo-real'               => 'Elmo Real',
            'elmo-demonio'            => 'Elmo Demoníaco',
            'elmo-judicante'          => 'Elmo Judicante',
            'elmo-tecelao-crepusculo' => 'Elmo de Tecelão do Crepúsculo',
            'elmo-da-bravura'         => 'Elmo da Bravura',
        ]],
    ]],

    // ── Armadura Calçado ────────────────────────────────────────────────────
    'armadura-calcado' => ['👟', 'Calçado', [
        'tecido' => ['Sapatos de Tecido', [
            'sandalias-erudito'    => 'Sandálias de Erudito',
            'sandalias-clerigo'    => 'Sandálias de Clérigo',
            'sandalias-mago'       => 'Sandálias de Mago',
            'sandalias-druida'     => 'Sandálias de Druida',
            'sandalias-real'       => 'Sandálias Real',
            'sandalias-malevolas'  => 'Sandálias Malévolas',
            'sandalias-sectarias'  => 'Sandálias Sectárias',
            'sandalias-feericas'   => 'Sandálias Feericas',
            'sandalias-da-pureza'  => 'Sandálias da Pureza',
        ]],
        'couro' => ['Sapatos de Couro', [
            'sapatos-mercenario'      => 'Sapatos de Mercenário',
            'sapatos-cacador'         => 'Sapatos de Caçador',
            'sapatos-assassino'       => 'Sapatos de Assassino',
            'sapatos-espreitador'     => 'Sapatos de Espreitador',
            'sapatos-reais'           => 'Sapatos Reais',
            'sapatos-inferiais'       => 'Sapatos Inferiais',
            'sapatos-espectrais'      => 'Sapatos Espectrais',
            'sapatos-andarilho-nevoa' => 'Sapatos de Andarilho da Névoa',
            'sapatos-da-tenacidade'   => 'Sapatos da Tenacidade',
        ]],
        'placa' => ['Sapatos de Placa', [
            'botas-soldado'            => 'Botas de Soldado',
            'botas-cavaleiro'          => 'Botas de Cavaleiro',
            'botas-guardiao'           => 'Botas de Guardião',
            'botas-guarda-tumbas'      => 'Botas de Guarda-Tumbas',
            'botas-reais'              => 'Botas Reais',
            'botas-deminias'           => 'Botas Demônias',
            'botas-judicantes'         => 'Botas Judicantes',
            'botas-tecelao-crepusculo' => 'Botas de Tecelão do Crepúsculo',
            'botas-da-bravura'         => 'Botas da Bravura',
            'botas-outros'             => 'Outros',
        ]],
    ]],

    // ── Mão Secundária ──────────────────────────────────────────────────────
    'mao-secundaria' => ['🪤', 'Mão Sec.', [
        'mago' => ['Mago', [
            'tomo-de-feiticos'     => 'Tomo de Feitiços',
            'olho-dos-segredos'    => 'Olho dos Segredos',
            'muisec'               => 'Muisec',
            'raiz-mestra'          => 'Raíz Mestra',
            'incensario-celeste'   => 'Incensário Celeste',
            'grimorio-estaguinado' => 'Grimório Estaguinado',
        ]],
        'cacador' => ['Caçador', [
            'tocha'            => 'Tocha',
            'brumario'         => 'Brumário',
            'bengala-maligna'  => 'Bengala Maligna',
            'lume-criptico'    => 'Lume Críptico',
            'cetro-sagrado'    => 'Cetro Sagrado',
            'tocha-chama-azul' => 'Tocha Chama Azul',
        ]],
        'guerreiro' => ['Guerreiro', [
            'escudo'           => 'Escudo',
            'sarcofago'        => 'Sarcófago',
            'escudo-vampirico' => 'Escudo Vampírico',
            'quebra-rostos'    => 'Quebra-Rostos',
            'egide-astral'     => 'Égide Astral',
            'barreira-inquebavel' => 'Barreira Inquebrável',
        ]],
    ]],

    // ── Capas ───────────────────────────────────────────────────────────────
    'capas' => ['🧥', 'Capas', [
        'capa'           => ['Capa', []],
        'bridgewatch'    => ['Bridgewatch', []],
        'fort-sterling'  => ['Fort Sterling', []],
        'lymhurst'       => ['Lymhurst', []],
        'martlock'       => ['Martlock', []],
        'thetford'       => ['Thetford', []],
        'caerleon'       => ['Caerleon', []],
        'brecilien'      => ['Brecilien', []],
        'hereges'        => ['Hereges', []],
        'mortos-vivos'   => ['Mortos-Vivos', []],
        'protetores'     => ['Protetores', []],
        'morgana'        => ['Morgana', []],
        'avaloniano'     => ['Avaloniano', []],
        'demonio'        => ['Demônio', []],
        'contrabandista' => ['Contrabandista', []],
    ]],

    // ── Bolsas ──────────────────────────────────────────────────────────────
    'bolsas' => ['🎒', 'Bolsas', [
        'bolsas-item'     => ['Bolsas', []],
        'sacola-da-visao' => ['Sacola da Visão', []],
    ]],

    // ── Montarias ───────────────────────────────────────────────────────────
    'montarias' => ['🐎', 'Montarias', [
        'montarias-base' => ['Montarias Base', [
            'cavalo'               => 'Cavalo',
            'cavalo-blindado'      => 'Cavalo Blindado',
            'boi'                  => 'Boi',
            'carneiros'            => 'Carneiros',
            'lobo'                 => 'Lobo',
            'viado-gigante'        => 'Viado Gigante',
            'garra-ligeira'        => 'Garra-Ligeira',
            'javali-vil'           => 'Javali-Vil',
            'urso'                 => 'Urso',
            'dragao-do-pantano'    => 'Dragão do Pantano',
            'mula'                 => 'Mula',
            'mamute'               => 'Mamute',
            'terrorbird'           => 'Terrorbird',
        ]],
        'montarias-raras' => ['Montarias Raras', [
            'cavalo-r'             => 'Cavalo',
            'cavalo-blindado-r'    => 'Cavalo Blindado',
            'carneiros-r'          => 'Carneiros',
            'lobo-r'               => 'Lobo',
            'garra-ligeira-r'      => 'Garra-Ligeira',
            'javali-vil-r'         => 'Javali-Vil',
            'urso-r'               => 'Urso',
            'dragao-do-pantano-r'  => 'Dragão do Pantano',
            'mula-r'               => 'Mula',
            'morcegos'             => 'Morcegos',
            'terrorbird-r'         => 'Terrorbird',
            'coruja'               => 'Coruja',
            'coelhos'              => 'Coelhos',
            'corvo'                => 'Corvo',
            'devorador'            => 'Devorador',
            'sapo'                 => 'Sapo',
        ]],
        'montarias-batalha' => ['Montarias de Batalha', [
            'bastiao-errante'        => 'Bastião Errante',
            'besouro-do-coloso'      => 'Besouro do Colosso',
            'behemoth'               => 'Behemoth',
            'carruagem-de-torre'     => 'Carruagem de Torre',
            'aguia-de-batalha'       => 'Águia de Batalha',
            'ent-ancestral'          => 'Ent Ancestral',
            'juggernaut'             => 'Juggernaut',
            'mamute-batalha'         => 'Mamute',
            'rinoceronte-batalha'    => 'Rinoceronte de Batalha',
            'balista-de-cerco'       => 'Balista de Cerco',
            'devorador-batalha'      => 'Devorador',
            'dragao-pantano-batalha' => 'Dragão do Pantano',
            'besouro-falange'        => 'Besouro Falange',
        ]],
    ]],

    // ── Consumíveis ─────────────────────────────────────────────────────────
    'consumiveis' => ['🍖', 'Consumíveis', [
        'comida' => ['Comida', [
            'sopa'           => 'Sopa',
            'saladas'        => 'Saladas',
            'tortas'         => 'Tortas',
            'assados'        => 'Assados',
            'omeletes'       => 'Omeletes',
            'guisados'       => 'Guisados',
            'sanduiches'     => 'Sanduíches',
            'peixe-grelhado' => 'Peixe Grelhado',
            'comida-evento'  => 'Evento',
        ]],
        'pocoes' => ['Poções', [
            'pocao-cura'         => 'Cura',
            'pocao-energia'      => 'Energia',
            'pocao-crescimento'  => 'De Crescimento',
            'pocao-resistencia'  => 'Resistência',
            'pocao-alvo'         => 'Alvo Persistente',
            'pocao-veneno'       => 'Veneno',
            'pocao-invisib'      => 'Invisibilidade',
            'pocao-calmante'     => 'Calmante',
            'pocao-purificadora' => 'Purificadora',
            'pocao-acido'        => 'Ácido',
            'pocao-furioso'      => 'Furioso',
            'pocao-infernais'    => 'Infernais',
            'pocao-coleta'       => 'Coleta',
            'pocao-tornado'      => 'Tornado',
            'pocao-foco'         => 'Foco',
            'pocao-evento'       => 'Evento',
        ]],
        'tomos' => ['Tomos', [
            'tomos-da-visao' => 'Tomos da Visão',
            'tomo-fibra'     => 'Fibra',
            'tomo-pelego'    => 'Pelego',
            'tomo-minerio'   => 'Minério',
            'tomo-pedra'     => 'Pedra',
            'tomo-madeira'   => 'Madeira',
        ]],
        'consumiveis-outros' => ['Outros', [
            'po-de-reparo'       => 'Pó de Reparo',
            'fogos-de-artificio' => 'Fogos de Artifício',
        ]],
    ]],

    // ── Equipamentos de Coleta ──────────────────────────────────────────────
    'equip-coleta' => ['⛏', 'Equip. Coleta', [
        'coleta-peixe' => ['Peixe', [
            'vara-de-pesca'    => 'Vara de Pesca',
            'roupas-pesca'     => 'Roupas',
            'chapeus-pesca'    => 'Chapéus',
            'botas-trabalho-p' => 'Botas de Trabalho',
            'mochila-pesca'    => 'Mochila',
            'isca'             => 'Isca',
        ]],
        'coleta-fibra' => ['Fibra', [
            'foice'            => 'Foice',
            'roupas-fibra'     => 'Roupas',
            'chapeus-fibra'    => 'Chapéus',
            'botas-trabalho-f' => 'Botas de Trabalho',
            'mochila-fibra'    => 'Mochila',
        ]],
        'coleta-pelego' => ['Pelego', [
            'faca-de-esfolar'   => 'Faca de Esfolar',
            'roupas-pelego'     => 'Roupas',
            'chapeus-pelego'    => 'Chapéus',
            'botas-trabalho-pe' => 'Botas de Trabalho',
            'mochila-pelego'    => 'Mochila',
        ]],
        'coleta-minerio' => ['Minério', [
            'picareta'          => 'Picareta',
            'roupas-minerio'    => 'Roupas',
            'chapeus-minerio'   => 'Chapéus',
            'botas-trabalho-m'  => 'Botas de Trabalho',
            'mochila-minerio'   => 'Mochila',
        ]],
        'coleta-pedra' => ['Pedra', [
            'martelo-coleta'    => 'Martelo',
            'roupas-pedra'      => 'Roupas',
            'chapeus-pedra'     => 'Chapéus',
            'botas-trabalho-pd' => 'Botas de Trabalho',
            'mochila-pedra'     => 'Mochila',
        ]],
        'coleta-madeira' => ['Madeira', [
            'machado-coleta'    => 'Machado',
            'roupas-madeira'    => 'Roupas',
            'chapeus-madeira'   => 'Chapéus',
            'botas-trabalho-ma' => 'Botas de Trabalho',
            'mochila-madeira'   => 'Mochila',
        ]],
        'coleta-rastreamento' => ['Rastreamento', [
            'kit-de-rastreamento' => 'Kit de Rastreamento',
        ]],
    ]],

    // ── Fabricação ──────────────────────────────────────────────────────────
    'fabricacao' => ['⚒', 'Fabricação', [
        'recursos' => ['Recursos', [
            'fibra'   => 'Fibra',
            'pelego'  => 'Pelego',
            'minerio' => 'Minério',
            'pedra'   => 'Pedra',
            'madeira' => 'Madeira',
        ]],
        'recursos-refinados' => ['Recursos Refinados', [
            'tecido'      => 'Tecido',
            'couro-ref'   => 'Couro',
            'barra-metal' => 'Barra de Metal',
            'barra-pedra' => 'Barra de Pedra',
            'tabua'       => 'Tábua',
        ]],
        'emblemas' => ['Emblemas', [
            'aprimoramentos-montaria' => 'Aprimoramentos de Montaria',
            'selo-real'               => 'Selo Real',
            'emblemas-outros'         => 'Outros',
        ]],
        'recursos-cidade' => ['Recursos da Cidade', [
            'coracao-bestial'    => 'Coração Bestial',
            'coracao-arborio'    => 'Coração Arbório',
            'coracao-montanhoso' => 'Coração Montanhoso',
            'coracao-empedrado'  => 'Coração Empedrado',
            'coracao-videira'    => 'Coração Videira',
            'coracao-sombrio'    => 'Coração Sombrio',
        ]],
        // 4 níveis: peixe-fab > peixe-comum/peixe-raro > espécie
        'peixe-fab' => ['Peixe', [
            'peixe-comum' => ['Comum', [
                'peixe-agua-doce' => 'Água Doce',
                'peixe-agua-salg' => 'Água Salgada',
            ]],
            'peixe-raro' => ['Raro', [
                'peixe-enguia'     => 'Enguia',
                'peixe-larario'    => 'Larápio',
                'peixe-olho-morto' => 'Olho Morto',
                'peixe-caranguejo' => 'Caranguejo',
                'peixe-mexilhoes'  => 'Mexilhões',
                'peixe-pargo'      => 'Pargo',
                'peixe-kraken'     => 'Kraken',
            ]],
            'peixe-outros-fab' => 'Outros',
        ]],
        'alquimia' => ['Alquimia', [
            'garras-sombrias'    => 'Garras Sombrias',
            'raiz-arboria'       => 'Raiz Arbória',
            'patas-espectrais'   => 'Patas Espectrais',
            'presas-lobisomem'   => 'Presas de Lobisomem',
            'chifre-de-diabrete' => 'Chifre de Diabrete',
            'dente-pedra-runica' => 'Dente de Pedra Rúnica',
            'pena-da-alvorada'   => 'Pena da Alvorada',
            'restos'             => 'Restos',
            'extrato-arcano'     => 'Extrato Arcano',
            'essencia'           => 'Essência',
        ]],
    ]],

    // ── Artefatos ───────────────────────────────────────────────────────────
    // 4 níveis: artefatos > grupo > tipo_arma > artefato_específico
    'artefatos' => ['💎', 'Artefatos', [
        'artefatos-armas' => ['Armas', [
            'art-arco'         => ['Arco', [
                'art-arco-badornico'  => 'Arco Badônico',
                'art-arco-plangente'  => 'Arco Plangente',
                'art-arco-sussurrante'=> 'Arco Sussurrante',
                'art-fura-brumas'     => 'Fura-Brumas',
                'art-arco-andarilho'  => 'Arco do Andarilho Celeste',
            ]],
            'art-besta'        => ['Besta', [
                'art-besta-arco-cerco'   => 'Arco de Cerco',
                'art-besta-laca-virotes' => 'Lança-Virotes',
                'art-besta-repetidor'    => 'Repetidor Lamentoso',
                'art-besta-modelador'    => 'Modelador de Energia',
                'art-besta-detonadores'  => 'Detonadores Reluzentes',
            ]],
            'art-machado'      => ['Machado', [
                'art-mach-chama'    => 'Chama-Corpos',
                'art-mach-seguad'   => 'Seguadeira Infernal',
                'art-mach-patas'    => 'Patas de Urso',
                'art-mach-quebra'   => 'Quebra Reinos',
                'art-mach-foice'    => 'Foice de Cristal',
            ]],
            'art-adaga'        => ['Adaga', [
                'art-adg-dessang' => 'Dessangrador',
                'art-adg-presa'   => 'Presa Demoníaca',
                'art-adg-mort'    => 'Mortíficos',
                'art-adg-furia'   => 'Fúria Contida',
                'art-adg-gemeas'  => 'Gêmeas Aniquiladoras',
            ]],
            'art-martelo'      => ['Martelo', [
                'art-mar-guardag'    => 'Guarda-Bosques',
                'art-mar-forja'      => 'Martelo de Forja',
                'art-mar-funebre'    => 'Martelo Fúnebre',
                'art-mar-justica'    => 'Mão da Justiça',
                'art-mar-estrond'    => 'Martelo Estrondoso',
            ]],
            'art-luvas'        => ['Luvas de Guerra', [
                'art-luv-ursinas'  => 'Luvas Ursinas',
                'art-luv-infern'   => 'Mãos Infernais',
                'art-luv-cestus'   => 'Cestus Golpeadores',
                'art-luv-avalon'   => 'Punhos de Avalon',
                'art-luv-pulsan'   => 'Braçadeiras Pulsantes',
            ]],
            'art-maca'         => ['Maça', [
                'art-mac-petrea'   => 'Maça Pétrea',
                'art-mac-incubus'  => 'Maça de Íncubus',
                'art-mac-cambr'    => 'Maça Cambriana',
                'art-mac-jurad'    => 'Jurador',
                'art-mac-monarca'  => 'Monarca Tempestuoso',
            ]],
            'art-bordao'       => ['Bordão', [
                'art-bor-equil'   => 'Cajado do Equilíbrio',
                'art-bor-segan'   => 'Seganímica',
                'art-bor-monge'   => 'Cajado de Monge Negro',
                'art-bor-graal'   => 'Buscador do Graal',
                'art-bor-laminas' => 'Lâminas Gêmeas Fantasmagóricas',
            ]],
            'art-lanca'        => ['Lança', [
                'art-lan-garc'    => 'Lança Garceira',
                'art-lan-caca'    => 'Caça-Espíritos',
                'art-lan-trina'   => 'Lança Trina',
                'art-lan-alvora'  => 'Alvorada',
                'art-lan-archa'   => 'Archa Fraturada',
            ]],
            'art-espada'       => ['Espada', [
                'art-esp-aclar'   => 'Lâmina Aclarada',
                'art-esp-entalh'  => 'Espada Entalhada',
                'art-esp-galat'   => 'Par de Galatinas',
                'art-esp-criareis'=> 'Cria-Reis',
                'art-esp-infin'   => 'Lâmina da Infinidade',
            ]],
            'art-cj-arcano'    => ['Cajado Arcano', [
                'art-cja-local'   => 'Local Malévolo',
                'art-cja-oculto'  => 'Cajado Oculto',
                'art-cja-feitiç'  => 'Cajado Feiticeiro',
                'art-cja-som'     => 'Som Equilíbrado',
                'art-cja-astral'  => 'Cajado Astral',
            ]],
            'art-cj-maldito'   => ['Cajado Amaldiçoado', [
                'art-cjm-danac'   => 'Cajado da Danação',
                'art-cjm-caveir'  => 'Caveira Amaldiçoada',
                'art-cjm-execr'   => 'Cajado Execrado',
                'art-cjm-chama'   => 'Chama-Sombra',
                'art-cjm-putr'    => 'Cajado Pútrido',
            ]],
            'art-cj-fogo'      => ['Cajado de Fogo', [
                'art-cjf-incend'  => 'Cajado Incendiário',
                'art-cjf-sulfu'   => 'Cajado Sulfuroso',
                'art-cjf-flame'   => 'Cajado Flamejante',
                'art-cjf-cancao'  => 'Canção da Alvorada',
                'art-cjf-andar'   => 'Cajado do Andarilho Flamejante',
            ]],
            'art-cj-gelo'      => ['Cajado de Gelo', [
                'art-cjg-enreg'   => 'Cajado Enregelante',
                'art-cjg-sinc'    => 'Cajado de Sincelo',
                'art-cjg-prisma'  => 'Prisma Geleterno',
                'art-cjg-uivo'    => 'Uivo Frio',
                'art-cjg-artico'  => 'Cajado Ártico',
            ]],
            'art-cj-sagrado'   => ['Cajado Sagrado', [
                'art-cjs-aviv'    => 'Cajado Avivador',
                'art-cjs-corr'    => 'Cajado Corrompido',
                'art-cjs-reden'   => 'Cajado da Redenção',
                'art-cjs-queda'   => 'Queda Santa',
                'art-cjs-exalt'   => 'Cajado Exaltado',
            ]],
            'art-cj-natureza'  => ['Cajado da Natureza', [
                'art-cjn-druid'   => 'Cajado Druídico',
                'art-cjn-pust'    => 'Cajado Pustulento',
                'art-cjn-ramp'    => 'Cajado Rampante',
                'art-cjn-raiz'    => 'Raiz Férrea',
                'art-cjn-crosta'  => 'Cajado de Crosta Forjado',
            ]],
            'art-cj-metamorfo' => ['Cajado Metamorfo', [
                'art-cjmt-runic'  => 'Cajado Rúnico da Terra',
                'art-cjmt-endem'  => 'Cajado Endemoniado',
                'art-cjmt-lua'    => 'Cajado da Lua de Sangue',
                'art-cjmt-invoc'  => 'Cajado Invocador da Luz',
                'art-cjmt-petr'   => 'Cajado Petrificante',
            ]],
        ]],
        'artefatos-peitoral' => ['Arm. Peitoral', [
            'art-peit-tecido' => ['Armadura de Tecido', [
                'art-peit-robe-druida'   => 'Robe de Druida',
                'art-peit-robe-malev'    => 'Robe Malévolo',
                'art-peit-robe-sect'     => 'Robe Sectário',
                'art-peit-robe-feer'     => 'Robe Feerico',
                'art-peit-robe-pureza'   => 'Robe da Pureza',
            ]],
            'art-peit-couro'  => ['Armadura de Couro', [
                'art-peit-cas-esp'   => 'Casaco de Espreitador',
                'art-peit-cas-inf'   => 'Casaco Inferial',
                'art-peit-cas-spec'  => 'Casaco Espectral',
                'art-peit-cas-and'   => 'Casaco de Andarilho',
                'art-peit-cas-ten'   => 'Casaco da Tenacidade',
            ]],
            'art-peit-placa'  => ['Armadura de Placa', [
                'art-peit-arm-judic'  => 'Armadura Judicante',
                'art-peit-arm-demon'  => 'Armadura Demônia',
                'art-peit-arm-guard'  => 'Armadura de Guarda-Tumbas',
                'art-peit-arm-tecel'  => 'Armadura de Tecelão do Crepúsculo',
                'art-peit-arm-brav'   => 'Armadura da Bravura',
            ]],
        ]],
        'artefatos-capacete' => ['Arm. Capacete', [
            'art-cap-tecido' => ['Capote de Tecido', [
                'art-cap-cap-druida' => 'Capote de Druida',
                'art-cap-cap-malev'  => 'Capote Malévolo',
                'art-cap-cap-sect'   => 'Capote Sectário',
                'art-cap-cap-feer'   => 'Capote Feerico',
                'art-cap-cap-pureza' => 'Capote da Pureza',
            ]],
            'art-cap-couro'  => ['Capuz de Couro', [
                'art-cap-cpz-esp'    => 'Capuz de Espreitador',
                'art-cap-cpz-inf'    => 'Capuz Inferial',
                'art-cap-cpz-spec'   => 'Capuz Espectral',
                'art-cap-cpz-and'    => 'Capuz de Andarilho da Névoa',
                'art-cap-cpz-ten'    => 'Capuz da Tenacidade',
            ]],
            'art-cap-placa'  => ['Elmo de Placa', [
                'art-cap-elmo-judic' => 'Elmo Judicante',
                'art-cap-elmo-demon' => 'Elmo Demônio',
                'art-cap-elmo-guard' => 'Elmo de Guarda-Tumbas',
                'art-cap-elmo-tecel' => 'Elmo de Tecelão do Crepúsculo',
                'art-cap-elmo-brav'  => 'Elmo da Bravura',
            ]],
        ]],
        'artefatos-calcados' => ['Calçados', [
            'art-calc-tecido' => ['Sapatos de Tecido', [
                'art-calc-sand-dru'  => 'Sandálias de Druida',
                'art-calc-sand-mal'  => 'Sandálias Malévolas',
                'art-calc-sand-sect' => 'Sandálias Sectárias',
                'art-calc-sand-feer' => 'Sandálias Feericas',
                'art-calc-sand-pur'  => 'Sandálias da Pureza',
            ]],
            'art-calc-couro'  => ['Sapatos de Couro', [
                'art-calc-sap-esp'   => 'Sapatos de Espreitador',
                'art-calc-sap-inf'   => 'Sapatos Inferiais',
                'art-calc-sap-spec'  => 'Sapatos Espectrais',
                'art-calc-sap-and'   => 'Sapatos de Andarilho da Névoa',
                'art-calc-sap-ten'   => 'Sapatos da Tenacidade',
            ]],
            'art-calc-placa'  => ['Sapatos de Placa', [
                'art-calc-bot-judic' => 'Botas Judicante',
                'art-calc-bot-demon' => 'Botas Demônias',
                'art-calc-bot-guard' => 'Botas de Guarda-Tumbas',
                'art-calc-bot-tecel' => 'Botas de Tecelão do Crepúsculo',
                'art-calc-bot-brav'  => 'Botas da Bravura',
            ]],
        ]],
        'artefatos-mao-sec' => ['Mão Secundária', [
            'art-ms-mago'      => ['Mago', [
                'art-ms-raiz'    => 'Raiz Mestra',
                'art-ms-muisec'  => 'Muisec',
                'art-ms-olho'    => 'Olho dos Segredos',
                'art-ms-incens'  => 'Incensário Celeste',
                'art-ms-grimor'  => 'Grimório Estaguinado',
            ]],
            'art-ms-cacador'   => ['Caçador', [
                'art-ms-brumario' => 'Brumário',
                'art-ms-bengala'  => 'Bengala Maligna',
                'art-ms-lume'     => 'Lume Críptico',
                'art-ms-cetro'    => 'Cetro Sagrado',
                'art-ms-tocha'    => 'Tocha Chama Azul',
            ]],
            'art-ms-guerreiro' => ['Guerreiro', [
                'art-ms-quebra'   => 'Quebra Rostos',
                'art-ms-escvamp'  => 'Escudo Vampírico',
                'art-ms-sarcof'   => 'Sarcófago',
                'art-ms-egide'    => 'Égide Astral',
                'art-ms-barr'     => 'Barreira Inquebrável',
            ]],
        ]],
        'fragmentos' => ['Fraguimentos', [
            'runas'                  => 'Runas',
            'almas'                  => 'Almas',
            'reliquias'              => 'Relíquias',
            'fragmentos-avalonianos' => 'Fraguimentos Avalonianos',
            'fragmentos-cristal'     => 'Fraguimentos de Cristal',
        ]],
        'artefatos-capas' => ['Capas', [
            'art-capa'           => 'Capa',
            'art-bridgewatch'    => 'Bridgewatch',
            'art-fort-sterling'  => 'Fort Sterling',
            'art-lymhurst'       => 'Lymhurst',
            'art-martlock'       => 'Martlock',
            'art-thetford'       => 'Thetford',
            'art-caerleon'       => 'Caerleon',
            'art-brecilien'      => 'Brecilien',
            'art-hereges'        => 'Hereges',
            'art-mortos-vivos'   => 'Morto-Vivo',
            'art-protetor'       => 'Protetor',
            'art-morgana'        => 'Morgana',
            'art-demonio'        => 'Demônio',
            'art-avaloniano'     => 'Avaloniano',
            'art-contrabandista' => 'Contrabandista',
        ]],
        'artefatos-cristalizados' => ['Artefatos Cristalizados', []],
    ]],

    // ── Cultivos ────────────────────────────────────────────────────────────
    // 4 níveis: cultivos > local > tipo > espécie
    'cultivos' => ['🌾', 'Cultivos', [
        'fazenda' => ['Fazenda', [
            'fazenda-sementes' => ['Sementes', [
                'sf-cenoura' => 'Cenouras',
                'sf-feijao'  => 'Feijões',
                'sf-trigo'   => 'Trigo',
                'sf-nabo'    => 'Nabo',
                'sf-repolho' => 'Repolhos',
                'sf-batata'  => 'Batata',
                'sf-milho'   => 'Milho',
                'sf-abobora' => 'Abóbora',
            ]],
            'fazenda-plantas' => ['Plantas', [
                'pf-cenoura' => 'Cenouras',
                'pf-feijao'  => 'Feijões',
                'pf-trigo'   => 'Trigo',
                'pf-nabo'    => 'Nabo',
                'pf-repolho' => 'Repolhos',
                'pf-batata'  => 'Batata',
                'pf-milho'   => 'Milho',
                'pf-abobora' => 'Abóbora',
            ]],
        ]],
        'horta' => ['Horta', [
            'horta-sementes' => ['Sementes', [
                'sh-agarico'   => 'Agárico',
                'sh-confrei'   => 'Confrei',
                'sh-bardana'   => 'Bardana',
                'sh-cardo'     => 'Cardo',
                'sh-dedaleira' => 'Dedaleira',
                'sh-verbasco'  => 'Verbasco',
                'sh-milefólio' => 'Milefólio',
            ]],
            'horta-ervas' => ['Ervas', [
                'eh-agarico'   => 'Agárico',
                'eh-confrei'   => 'Confrei',
                'eh-bardana'   => 'Bardana',
                'eh-cardo'     => 'Cardo',
                'eh-dedaleira' => 'Dedaleira',
                'eh-verbasco'  => 'Verbasco',
                'eh-milefólio' => 'Milefólio',
            ]],
        ]],
        'pasto' => ['Pasto', [
            'pasto-filhotes' => ['Filhotes de Animais', [
                'fp-galinha' => 'Galinha',
                'fp-cabra'   => 'Cabra',
                'fp-ganso'   => 'Ganso',
                'fp-ovelha'  => 'Ovelha',
                'fp-porco'   => 'Porco',
                'fp-vaca'    => 'Vaca',
                'fp-cavalo'  => 'Cavalo',
                'fp-boi'     => 'Boi',
                'fp-alce'    => 'Alce',
                'fp-veado'   => 'Veado/Alce',
            ]],
            'pasto-animais' => ['Animal', [
                'ap-galinha' => 'Galinha',
                'ap-cabra'   => 'Cabra',
                'ap-ganso'   => 'Ganso',
                'ap-ovelha'  => 'Ovelha',
                'ap-porco'   => 'Porco',
                'ap-vaca'    => 'Vaca',
                'ap-cavalo'  => 'Cavalo',
                'ap-boi'     => 'Boi',
                'ap-alce'    => 'Alce',
                'ap-veado'   => 'Veado/Alce',
            ]],
            'pasto-ovos'  => ['Ovos', []],
            'pasto-leite' => ['Leite', []],
        ]],
        'canil' => ['Canil', [
            'canil-filhotes' => ['Filhotes de Animais', [
                'fc-garra-ligeira'  => 'Garra-Ligeira',
                'fc-lobo'           => 'Lobo',
                'fc-javali-vil'     => 'Javali-Vil',
                'fc-urso'           => 'Urso',
                'fc-mamute'         => 'Mamute',
                'fc-dragao-pantano' => 'Dragão do Pantano',
                'fc-terrorbird'     => 'Terrorbird',
                'fc-coruja'         => 'Coruja',
                'fc-coelhos'        => 'Coelhos',
                'fc-carneiros'      => 'Carneiros',
                'fc-devorador'      => 'Devorador',
            ]],
            'canil-animais' => ['Animal', [
                'ac-garra-ligeira'  => 'Garra-Ligeira',
                'ac-lobo'           => 'Lobo',
                'ac-javali-vil'     => 'Javali-Vil',
                'ac-urso'           => 'Urso',
                'ac-mamute'         => 'Mamute',
                'ac-dragao-pantano' => 'Dragão do Pantano',
                'ac-terrorbird'     => 'Terrorbird',
                'ac-coruja'         => 'Coruja',
                'ac-coelhos'        => 'Coelhos',
                'ac-carneiros'      => 'Carneiros',
                'ac-devorador'      => 'Devorador',
            ]],
        ]],
        'produtos-cultivados' => ['Produtos Cultivados', [
            'alcool'   => 'Álcool',
            'pao'      => 'Pão',
            'manteiga' => 'Manteiga',
            'farinha'  => 'Farinha',
            'carne'    => 'Carne',
        ]],
    ]],

    // ── Mobília ─────────────────────────────────────────────────────────────
    'mobilia' => ['🏠', 'Mobília', [
        'kit-reparo'    => ['Kit de Reparo', []],
        'bau'           => ['Baú', [
            'bau-casa'  => 'Casa',
            'bau-mundo' => 'Mundo',
        ]],
        'mobilia-casa'  => ['Casa', []],
        'mobilia-ilha'  => ['Ilha', []],
        'mobilia-mundo' => ['Mundo', [
            'estante'        => 'Estante',
            'estatuas'       => 'Estátuas',
            'mobilia-outros' => 'Outros',
        ]],
    ]],

    // ── Vaidades ────────────────────────────────────────────────────────────
    'vaidades' => ['✨', 'Vaidades', [
        'vaidade-montarias' => ['Montarias', [
            'vaid-cavalo'        => 'Cavalo',
            'vaid-cavalo-blind'  => 'Cavalo Blindado',
            'vaid-boi'           => 'Boi',
            'vaid-lobo'          => 'Lobo',
            'vaid-veado'         => 'Veado/Alce',
            'vaid-garra-ligeira' => 'Garra-Ligeira',
            'vaid-javali'        => 'Javali-Vil',
            'vaid-urso'          => 'Urso',
            'vaid-dragao'        => 'Dragão do Pantano',
            'vaid-mula'          => 'Mula',
            'vaid-mamute'        => 'Mamute',
        ]],
        'vaidade-armas'        => ['Armas', []],
        'vaidade-peitoral'     => ['Arm. Peitoral', []],
        'vaidade-capacete'     => ['Arm. Capacete', []],
        'vaidade-calcados'     => ['Calçados', []],
        'vaidade-mao-sec'      => ['Mão Secundária', []],
        'vaidade-capas'        => ['Capas', []],
        'vaidade-emotes-morte' => ['Emotes de Morte', []],
    ]],

    // ── Outros ──────────────────────────────────────────────────────────────
    'outros' => ['📦', 'Outros', [
        'guilda' => ['Guilda', [
            'esconderijo'      => 'Esconderijo',
            'martelo-de-cerco' => 'Martelo de Cerco',
            'estandarte-cerco' => 'Estandarte de Cerco',
        ]],
        // 4 níveis: outros > trabalhadores > tipo > item
        'trabalhadores' => ['Trabalhadores', [
            'trab-diarios' => ['Diários', [
                'diario-geral'         => 'Geral',
                'diario-peixe'         => 'Peixe',
                'diario-fibra'         => 'Fibra',
                'diario-pelego'        => 'Pelego',
                'diario-minerio'       => 'Minério',
                'diario-pedra'         => 'Pedra',
                'diario-madeira'       => 'Madeira',
                'diario-cacador'       => 'Caçador',
                'diario-mago'          => 'Mago',
                'diario-guerreiro'     => 'Guerreiro',
                'diario-ferramenteiro' => 'Ferramenteiro',
                'diario-mercenario'    => 'Mercenário',
            ]],
            'trab-trofeus' => ['Troféus', [
                'trofeu-geral'      => 'Geral',
                'trofeu-peixe'      => 'Peixe',
                'trofeu-fibra'      => 'Fibra',
                'trofeu-pelego'     => 'Pelego',
                'trofeu-minerio'    => 'Minério',
                'trofeu-pedra'      => 'Pedra',
                'trofeu-madeira'    => 'Madeira',
                'trofeu-mercenario' => 'Mercenário',
                'trofeu-outros'     => 'Outros',
            ]],
            'trab-contratos' => ['Contratos', [
                'contrato-peixe'         => 'Peixe',
                'contrato-fibra'         => 'Fibra',
                'contrato-pelego'        => 'Pelego',
                'contrato-minerio'       => 'Minério',
                'contrato-pedra'         => 'Pedra',
                'contrato-madeira'       => 'Madeira',
                'contrato-cacador'       => 'Caçador',
                'contrato-mago'          => 'Mago',
                'contrato-guerreiro'     => 'Guerreiro',
                'contrato-ferramenteiro' => 'Ferramenteiro',
                'contrato-mercenario'    => 'Mercenário',
            ]],
            'trab-camas' => 'Camas',
            'trab-mesas' => 'Mesas',
        ]],
        'emblemas-outros' => ['Emblemas', [
            'emblema-vaidade'     => 'Vaidade',
            'token-liga-cristal'  => ['Token da Liga de Cristal', [
                'token-5vs5'   => '5vs5',
                'token-20vs20' => '20vs20',
            ]],
            'emblema-ancora'  => 'Âncora',
            'emblema-outros'  => 'Outros',
        ]],
        'bens-de-luxo' => ['Bens de Luxo', [
            'luxo-bridgewatch'   => 'Bridgewatch',
            'luxo-fort-sterling' => 'Fort Sterling',
            'luxo-lymhurst'      => 'Lymhurst',
            'luxo-martlock'      => 'Martlock',
            'luxo-thetford'      => 'Thetford',
            'luxo-caerleon'      => 'Caerleon',
            'luxo-qualquer'      => 'Qualquer',
        ]],
        // 4 níveis: outros > mapa > tipo > modo
        'mapa' => ['Mapa', [
            'mrand' => ['Masmorras Randomizadas', [
                'mrand-solo'     => 'Solo',
                'mrand-grupo'    => 'Grupo',
                'mrand-invasoes' => 'Invasões',
            ]],
            'mcorr' => ['Masmorras Corrompidas', [
                'mcorr-nao-letal' => 'Não Letal',
                'mcorr-letal'     => 'Letal',
            ]],
            'hellgates' => ['Hellgates', [
                'hg-nao-letal' => 'Não Letal',
                'hg-letal'     => 'Letal',
            ]],
        ]],
        'exped-hardcore' => ['Expedições Hardcore', [
            'exped-evento'        => 'Evento',
            'negocios-suspeitos'  => 'Negócios Suspeitos',
            'punhado-de-prata'    => 'Punhado de Prata',
            'loucura-madereira'   => 'Loucura Madereira',
            'fungicida'           => 'Fungicida',
            'reza-mortos'         => 'Reza Para os Mortos',
            'espeita-subterranea' => 'Espeita Subterânea',
            'guerras-rochosas'    => 'Guerras Rochosas',
            'tres-irmas'          => 'Três Irmãs',
            'garras-do-corvo'     => 'Nas Garras do Corvo',
            'batalha-eterna'      => 'Batalha Eterna',
        ]],
        // 4 níveis: outros > itens-missao > missao-cidade > cidade
        'itens-missao' => ['Itens de Missão', [
            'missao-cidade' => ['Cidade', [
                'missao-bridgewatch'   => 'Bridgewatch',
                'missao-fort-sterling' => 'Fort Sterling',
                'missao-lymhurst'      => 'Lymhurst',
                'missao-martlock'      => 'Martlock',
                'missao-thetford'      => 'Thetford',
                'missao-caerleon'      => 'Caerleon',
            ]],
            'missao-outros' => 'Outros',
        ]],
    ]],

];
